### ISSUE TITLE
Python-PCL "NameError: global name 'PointCloud' is not defined" when running 

### ISSUE THREAD

**Issue by pbach3** [strawlab/python-pcl#105]
Hello,

I am new to PCL. After multiple attempts to make the library work I believe it is finally up and ready. However, I have been stopped by "NameError: global name 'PointCloud' is not defined" when running PCL through Python-PCL (https://github.com/strawlab/python-pcl). I am not sure if it is a small tweak that is required in the __init__.py that has been provided or if this is masking another error I am unaware of. The error has come up when I have tried running an example script:

import pcl
p = pcl.load("C/table_scene_lms400.pcd")
fil = p.make_statistical_outlier_filter()
fil.set_mean_k (50)
fil.set_std_dev_mul_thresh (1.0)
fil.filter().to_file("inliers.pcd")

Error message:
  File "smoothng.py", line 2, in <module>
    p = pcl.load("/C/table_scene_lms400.pcd")
  File "/usr/local/lib/python2.7/dist-packages/pcl/__init__.py", line 15, in load
    p = PointCloud()
NameError: global name 'PointCloud' is not defined

Thank You

**Comment by pbach3** [comment]
p = pcl.PointCloud()
p.from_file(("C/table_scene_lms400.pcd")
fil = p.make_statistical_outllier_filter()
fil.set_mean(mean)
fil.set_std_dev_mul_thresh(standardDeviation)
fil.filter().to_file(outputInlierPointCloud)

This lets the script run. Posting as a reference if anyone has the same question.

**Comment by washburn125** [comment]
Hello! I am running this:
p = pcl.PointCloud()
p.from_file(("C/table_scene_lms400.pcd")
fil = p.make_statistical_outllier_filter()
fil.set_mean(mean)
fil.set_std_dev_mul_thresh(standardDeviation)
fil.filter().to_file(outputInlierPointCloud)

but I still have 
AttributeError                            Traceback (most recent call last)
<ipython-input-90-a9f819069335> in <module>
      1 import pcl
----> 2 p = pcl.PointCloud()
      3 p.from_file("banana_1_1_3.pcd")
      4 fil = p.make_statistical_outllier_filter()
      5 fil.set_mean(mean)

AttributeError: module 'pcl' has no attribute 'PointCloud'

**Comment by psanzgalar** [comment]
hello:
I have the same error, were you able to fix it?
