### ISSUE TITLE
Module has no attribute registration 

### ISSUE THREAD

**Issue by s0972456** [strawlab/python-pcl#120]
Hello,
I installed pcl 1.8.1 and python pcl successfully , I  used some functions in the PointCloud class without a problem but when I was trying to use the iterative closest point methods I got an error saying module has no attribute registration.

**Comment by s0972456** [comment]
I figured this out...the issue was on my side.

**Comment by Siladon** [comment]
s0972456 how did you solve your problem?

**Comment by cissy123** [comment]
i have the same problem. i can successfully import pcl, but error 'has no attribute ...'. how did you solve it?
