### ISSUE TITLE
Error PointCloud.from_file TypeError: expected bytes, str found

### ISSUE THREAD

**Issue by felipebsferreira** [strawlab/python-pcl#121]
I'm trying to load a pcd file from its name but I always get an error. I'm using pcd files from pcl tutorials, for example "table_scene_mug_stereo_textured.pcd". Here an example of code I'm running and the error I get:

Code:

import pcl

p = pcl.PointCloud()
p.from_file("lamppost.pcd")

Error:

Traceback (most recent call last):
  File "/home/felipe/Dropbox/Projetos/Python/PráticasPDI/teste_pcl.py", line 5, in <module>
    p.from_file("lamppost.pcd")
  File "pcl/pxi/PointCloud_PointXYZ_172.pxi", line 223, in pcl._pcl.PointCloud.from_file
TypeError: expected bytes, str found
[Finished in 0.2s with exit code 1]
[shell_cmd: python3 -u "/home/felipe/Dropbox/Projetos/Python/PráticasPDI/teste_pcl.py"]
[dir: /home/felipe/Dropbox/Projetos/Python/PráticasPDI]
[path: /home/felipe/bin:/home/felipe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin]

**Comment by Sirokujira** [comment]
If you would like to read the file, the following processing is recommended.

import pcl
p = pcl.load ("lamppost.pcd")

The processing flow with load(),
a. Determine an extension from a character string (pcl/ply), and perform a process of passing a function corresponding to the reading of the file in the extension to the variable.
b. Perform processing to convert character strings to binary character strings.
c. Call the function set in a.
   (pcd -> _from_pcd_file)
   (ply -> _from_ply_file)

* Please check the pcl/__init__.py source code.

If you call it by the above method,

p.from_file (b "lamppost.pcd")

As a binary string it must be passed as.

**Comment by Sirokujira** [comment]
If you would like to read the file, the following processing is recommended.

import pcl
p = pcl.load ("lamppost.pcd")

The processing flow with load(),
a. Determine an extension from a character string (pcl/ply), and perform a process of passing a function corresponding to the reading of the file in the extension to the variable.
b. Perform processing to convert character strings to binary character strings.
c. Call the function set in a.
   (pcd -> _from_pcd_file)
   (ply -> _from_ply_file)

* Please check the `pcl/__init__.py` source code.

If you call it by the above method,

p.from_file(b"lamppost.pcd")

As a binary string it must be passed as.

**Comment by felipebsferreira** [comment]
Ok, thanks. It worked.
