### ISSUE TITLE
Point cloud visualization issue

### ISSUE THREAD

**Issue by EsrtG** [strawlab/python-pcl#124]
Hi everyone,

I have an issue about the visualization of a PointCloud_PointXYZI object build on np.array
Here my code : 

`import numpy as np
import random
import scipy as sc
from laspy import file
import pcl
from pcl import pcl_visualization

#laspy librairy, read las file
f = file.File('myPointCloud.las',mode='r')
#Store pointcloud in array
ptcloud = np.vstack((f.x, f.y, f.z)).transpose()
f.close()

#Centred the data
ptcloud_centred = ptcloud - np.mean(ptcloud,0)

#Simulate an intensity information between 0 and 1
ptcloud_centred = sc.append(ptcloud_centred,np.zeros((ptcloud.shape[0],1)),axis=1) # Ajout d'une ligne (axis=0)
for i in range(ptcloud_centred.shape[0]-1):
    ptcloud_centred[i,3] = random.random()
    
# Create a PointCloud Object 
p = pcl.PointCloud_PointXYZI()
p.from_array(np.array(ptcloud_centred, dtype=np.float32))

##Visualization
visual = pcl_visualization.CloudViewing()
visual.ShowGrayCloud(p)`

A Message error told me : 
TypeError: expected bytes, str found

The thing is without intensity information a similar code works : 

`import numpy as np
import random
import scipy as sc
from laspy import file
import pcl
from pcl import pcl_visualization

#laspy librairy, read las file
f = file.File('myPointCloud.las',mode='r')
#Store pointcloud in array
ptcloud = np.vstack((f.x, f.y, f.z)).transpose()
f.close()

#Centred the data
ptcloud_centred = ptcloud - np.mean(ptcloud,0)
    
# Create a PointCloud Object 
p = pcl.PointCloud(np.array(ptcloud_centred, dtype=np.float32))

##Visualization
visual = pcl_visualization.CloudViewing()
visual.ShowMonochromeCloud(p)`

Thenak you in adavance for your help

**Comment by Sirokujira** [comment]
As a cause of the error,
In the ShowGrayCloud function of CloudViewing.pxi,
Set the cloudname argument to the default setting string
It is because we have not passed a binary string.

Therefore, when calling a function, you need to pass a binary string to the cloudname.

ex. 
visual.ShowGrayCloud(p, b'cloud')

**Comment by EsrtG** [comment]
Great! It works!
Many thanks!

**Comment by niranjanreddy891** [comment]
I am unable to import pcl_ visualization.
Please refer this. This is the error I am facing.
Please help me in solving this issue
https://github.com/strawlab/python-pcl/issues/164
