### ISSUE TITLE
PointcloudXYZI asarray.

### ISSUE THREAD

**Issue by jacoblambert** [strawlab/python-pcl#134]
Hi there,
I'm experiencing some strange behavior while trying to convert a XYZI point cloud to numpy array. 

```
    filename = "../test.pcd"
    pcl_cloud = pcl.load_XYZI(filename)

    np_cloud = np.empty([pcl_cloud.width, 4], dtype=np.float32)
    np_cloud = np.asarray(pcl_cloud)
    print(pcl_cloud[0])
    (7.586839199066162, -10.320956230163574, -1.3337143659591675, 162.0)
    print(np_cloud[0])
    [  7.58683920e+00  -1.03209562e+01  -1.33371437e+00   4.58659000e-41]
    print(pcl_cloud[0][3])
    162.0
    print(np_cloud[0][3])
    4.58659e-41

However if I asarray a line of the point cloud..

    np_cloud = np.empty([pcl_cloud.width, 4], dtype=np.float32)
    np_cloud = np.asarray(pcl_cloud[0])
    print(np_cloud)
    [   7.5868392   -10.32095623   -1.33371437  162.        ]
    print(np_cloud[3])
    162.0
```

Sorry if this turns out to be more about how np.asarray works than how python-pcl works, but I haven't found an answer in numpy documentation. 
Thanks for your time.

**Comment by Sirokujira** [comment]
PointCloud_XYZI data If you want to use it as an array of numpy, please do as follows.

np_cloud = np.empty([pcl_cloud.width, 4], dtype=np.float32)
np_cloud = np.asarray(pcl_cloud)
↓
np_cloud = pcl_cloud.to_array()

**Comment by jacoblambert** [comment]
I see, works perfectly. Thank you so much!

**Comment by chaiban** [comment]
Hi, is there a possibility to convert numpy array to point cloud ? 
p = pcl.PointCloud()
keypoints_p = p.from_array(np.array(np_keypoints) , dtype= np.float32)
print(keypoints_p)

I tried this was and its not working. i am new to pointcloud and iam getting confused.

Thank you for your help
