### ISSUE TITLE
Unable to build on Ubuntu16.04 with python3.5

### ISSUE THREAD

**Issue by YvetteLaw** [strawlab/python-pcl#142]
PCL1.8
Ubuntu16.04
Python 3.5
Cython 0.25.2

when I try to build Python-pcl，this error appears, even when I tend to PCL1.7.

$ :~/py3.5_tf1.2_virtu/python_pcl/python-pcl-master$ make
python setup.py build_ext --inplace
running build_ext
skipping 'pcl/_pcl_180.cpp' Cython extension (up-to-date)
building 'pcl._pcl' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DEIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET=1 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/pcl-1.8 -I/usr/local/include -I/usr/local/include/pcl-1.8 -I/usr/include/ni -I/usr/include/eigen3 -I/usr/include/ni -I/usr/include/python2.7 -c pcl/_pcl_180.cpp -o build/temp.linux-x86_64-2.7/pcl/_pcl_180.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1781:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pcl/_pcl_180.cpp:526:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from pcl/_pcl_180.cpp:634:0:
/usr/local/include/pcl-1.8/pcl/keypoints/uniform_sampling.h:44:2: warning: #warning UniformSampling is not a Keypoint anymore, use <pcl/filters/uniform_sampling.h> instead. [-Wcpp]
 #warning UniformSampling is not a Keypoint anymore, use <pcl/filters/uniform_sa
  ^
pcl/_pcl_180.cpp: In function ‘PyObject* __pyx_pf_3pcl_4_pcl_18MovingLeastSquares_8set_polynomial_fit(__pyx_obj_3pcl_4_pcl_MovingLeastSquares*, bool)’:
pcl/_pcl_180.cpp:29142:49: warning: ‘void pcl::MovingLeastSquares<PointInT, PointOutT>::setPolynomialFit(bool) [with PointInT = pcl::PointXYZ; PointOutT = pcl::PointXYZ]’ is deprecated: [pcl::surface::MovingLeastSquares::setPolynomialFit] setPolynomialFit is deprecated. Please use setPolynomialOrder instead. [-Wdeprecated-declarations]
   __pyx_v_self->me->setPolynomialFit(__pyx_v_fit);
                                                 ^
In file included from pcl/_pcl_180.cpp:554:0:
/usr/local/include/pcl-1.8/pcl/surface/mls.h:356:7: note: declared here
       setPolynomialFit (bool polynomial_fit)
       ^
pcl/_pcl_180.cpp: In function ‘PyObject* __pyx_pf_3pcl_4_pcl_30MovingLeastSquares_PointXYZRGB_8set_polynomial_fit(__pyx_obj_3pcl_4_pcl_MovingLeastSquares_PointXYZRGB*, int)’:
pcl/_pcl_180.cpp:29625:49: warning: ‘void pcl::MovingLeastSquares<PointInT, PointOutT>::setPolynomialFit(bool) [with PointInT = pcl::PointXYZRGB; PointOutT = pcl::PointXYZRGB]’ is deprecated: [pcl::surface::MovingLeastSquares::setPolynomialFit] setPolynomialFit is deprecated. Please use setPolynomialOrder instead. [-Wdeprecated-declarations]
   __pyx_v_self->me->setPolynomialFit(__pyx_v_fit);
                                                 ^
In file included from pcl/_pcl_180.cpp:554:0:
/usr/local/include/pcl-1.8/pcl/surface/mls.h:356:7: note: declared here
       setPolynomialFit (bool polynomial_fit)
       ^
pcl/_pcl_180.cpp: In function ‘PyObject* __pyx_pf_3pcl_4_pcl_31MovingLeastSquares_PointXYZRGBA_8set_polynomial_fit(__pyx_obj_3pcl_4_pcl_MovingLeastSquares_PointXYZRGBA*, int)’:
pcl/_pcl_180.cpp:29991:49: warning: ‘void pcl::MovingLeastSquares<PointInT, PointOutT>::setPolynomialFit(bool) [with PointInT = pcl::PointXYZRGBA; PointOutT = pcl::PointXYZRGBA]’ is deprecated: [pcl::surface::MovingLeastSquares::setPolynomialFit] setPolynomialFit is deprecated. Please use setPolynomialOrder instead. [-Wdeprecated-declarations]
   __pyx_v_self->me->setPolynomialFit(__pyx_v_fit);
                                                 ^
In file included from pcl/_pcl_180.cpp:554:0:
/usr/local/include/pcl-1.8/pcl/surface/mls.h:356:7: note: declared here
       setPolynomialFit (bool polynomial_fit)
       ^
pcl/_pcl_180.cpp: In function ‘int __pyx_pf_3pcl_4_pcl_18ConditionalRemoval___cinit__(__pyx_obj_3pcl_4_pcl_ConditionalRemoval*, __pyx_obj_3pcl_4_pcl_ConditionAnd*)’:
pcl/_pcl_180.cpp:46441:145: error: no matching function for call to ‘pcl::ConditionalRemoval<pcl::PointXYZ>::ConditionalRemoval(__pyx_t_3pcl_11pcl_filters_ConditionBasePtr_t, NULL)’
 val_t(((__pyx_t_3pcl_11pcl_filters_ConditionBasePtr_t)__pyx_v_cond->me), NULL);
                                                                              ^
In file included from pcl/_pcl_180.cpp:531:0:
/usr/local/include/pcl-1.8/pcl/filters/conditional_removal.h:618:7: note: candidate: pcl::ConditionalRemoval<PointT>::ConditionalRemoval(int) [with PointT = pcl::PointXYZ]
       ConditionalRemoval (int extract_removed_indices = false) :
       ^
/usr/local/include/pcl-1.8/pcl/filters/conditional_removal.h:618:7: note:   candidate expects 1 argument, 2 provided
/usr/local/include/pcl-1.8/pcl/filters/conditional_removal.h:594:9: note: candidate: pcl::ConditionalRemoval<pcl::PointXYZ>::ConditionalRemoval(const pcl::ConditionalRemoval<pcl::PointXYZ>&)
   class ConditionalRemoval : public Filter<PointT>
         ^
/usr/local/include/pcl-1.8/pcl/filters/conditional_removal.h:594:9: note:   candidate expects 1 argument, 2 provided
pcl/_pcl_180.cpp: At global scope:
pcl/_pcl_180.cpp:49917:12: warning: ‘int __pyx_pw_3pcl_4_pcl_21RandomSampleConsensus_1__cinit__(PyObject*, PyObject*, PyObject*)’ defined but not used [-Wunused-function]
 static int __pyx_pw_3pcl_4_pcl_21RandomSampleConsensus_1__cinit__(PyObject *__p
            ^
pcl/_pcl_180.cpp:50007:12: warning: ‘int __pyx_pw_3pcl_4_pcl_21RandomSampleConsensus_3__cinit__(PyObject*, PyObject*, PyObject*)’ defined but not used [-Wunused-function]
 static int __pyx_pw_3pcl_4_pcl_21RandomSampleConsensus_3__cinit__(PyObject *__p
            ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Makefile:5: recipe for target 'pcl/_pcl.so' failed
make: *** [pcl/_pcl.so] Error 1

**Comment by YvetteLaw** [comment]
Is this  duplicate? I've check my PCL1.8 and make sure that it's installed successfully. But this error still exists.

**Comment by leaveitout** [comment]
I was receiving this error because I had compiled PCL from master, where the ConditionalRemoval constructor has been removed (where it was previously just marked deprecated), causing the same error as above. I fixed it by cloning PCL from the 1.8.1 tag and rebuilding it.

**Comment by tryssss** [comment]
I got the same problem like you, and I try the method introduced by @leaveitout. I fixed it finally!

**Comment by ljc19800331** [comment]
I got the same error also. Would it possible if you @leaveitout @tryssss  show me solution step by step? I have the confusions like:

1."compile PCL from master" -- I don't know the exact meaning.
2."cloning PCL from 1.8.1 tag" -- Does it mean that to clone the pcl 1.8.1 from github and rebuild it? What would be the different with the previous process?

Thank you very much. I really need this help.

**Comment by tryssss** [comment]
@ljc19800331 , sorry, I don't have time to read your text. But I can give you the step what I use to figure out my problem..
wget https://github.com/PointCloudLibrary/pcl/archive/pcl-1.8.1.tar.gz
tar -xf pcl-1.8.1.tar.gz
cd pcl-pcl-1.8.1 && mkdir build && cd build
cmake ..
make
sudo make install

Then rebuild the Python-PCL. Good luck!

**Comment by ljc19800331** [comment]
@tryssss  Thanks for your quick reply. 

Are you using python 3 or python 2 (could you give me a version?).
Any other setting I need to make after building the python-PCL, or it just install successfully and we don't need to change anything?

Thanks for your reply.
