### ISSUE TITLE
unable to use make_VexelGrid()

### ISSUE THREAD

**Issue by ansabsheikh9** [strawlab/python-pcl#143]
hi,
I am trying to use it but it is giving me this error. Kindly help.
I am trying to convert point cloud into some voxel grid.  For examlple vovel of (80,80,80)

 cloud.make_VexelGrid()
AttributeError: 'pcl._pcl.PointCloud' object has no attribute 'make_VexelGrid

**Comment by Sirokujira** [comment]
make_VexelGrid() replace make_voxel_grid_filter()

**Comment by ansabsheikh9** [comment]
thank you for you reply
