### ISSUE TITLE
windows Install Error

### ISSUE THREAD

**Issue by Qipccc** [strawlab/python-pcl#163]
I have installed PCL 18.1 and gtk+，but when I excute "python setup.py build_ext -i" it has error :

LINK : fatal error LNK1104: cannot open file 'libboost_date_time-vc140-mt-1_64.lib'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1104

**Comment by ymwtz** [comment]
I guess you used wrong PCL installer.
I used PCL-1.8.1-AllInOne-msvc2017-win64.exe to install PCL, and I find the libboost version is  vc141. So I used PCL-1.8.1-AllInOne-msvc2015-win64.exe.

**Comment by Qipccc** [comment]
when i re-install it, it was solved.i don't know what's wrong before

**Comment by niranjanreddy891** [comment]
Ok. Close the issue if the issue is solved. :)

**Comment by scizors** [comment]
ya thanks for this
