### ISSUE TITLE
Any sample for visualization?

### ISSUE THREAD

**Issue by hyperknot** [strawlab/python-pcl#17]
I'm looking forward to using python-pcl, however I'd need to have at least some visual feedback for checking the point cloud dataset while experimenting with methods/algorithms.

Is there any working sample for visualizing a point cloud dataset under Python? I'm thinking about Matplotlib if it's fast enough or possibly a PyOpenGL viewer? Has anyone done anything similar?

**Comment by rohanbhargava11** [comment]
Any update on this? Is there a Python wrapper for the viewer in PCL?

**Comment by nzjrs** [comment]
no, I just use matplotlib

**Comment by toinsson** [comment]
you can use the visualisation from VTK (which is used by PCL) as they have good python bindings.
http://www.vtk.org/Wiki/VTK/Examples/Python

**Comment by eugeneu** [comment]
@toinsson is there an example of converting PointCloud object to VTK object to display?

**Comment by toinsson** [comment]
there's a pointer:
https://github.com/toinsson/pyrealsense/blob/master/examples/show_vtk.py
in this case, it is streaming the data but you don't have to use the threadlock nor the update.
