### ISSUE TITLE
How to visualize LAS data for RGB colors using PCL

### ISSUE THREAD

**Issue by niranjanreddy891** [strawlab/python-pcl#171]
`p = pcl.PointCloud_PointXYZI()`  # for intensity
`p = pcl.PointCloud_PointXYZRGB()` # for RGB

These commands I am using but the code works fine for Intensity. But wheen I am giving `RGB`in place of `I`, it throws error saying that `TypeError: Argument 'pc' has incorrect type (expected pcl._pcl.PointCloud_PointXYZI, got pcl._pcl.PointCloud_PointXYZRGB)
`. Please help me in this issue

**Comment by pablogago11** [comment]
I suspect that you have initialized the variable p as a XYZI point cloud and then you are calling the same variable p to be RGB. Call the RGB point cloud as prgb for instance as Python has already p in the variable workspace.

**Comment by niranjanreddy891** [comment]
@pablogago11, I gave an example of intensity which works fine. But with RGB, it is not working. Please help me

**Comment by niranjanreddy891** [comment]
@pablogago11, where to specify RGB colors in this `ptcloud = np.vstack((f.x, f.y, f.z)).transpose()`. Can you help me

**Comment by pablogago11** [comment]
@niranjanreddy891 I am not an expert but Python cannot handle as Matlab with renamed variables, once you define a name and a type Python language cannot change the type of the variable as you did in the previous comment. Also, PointXYZRGB clouds, if you take a look at the documentation, they have X, Y, Z components and a float for the RGB value. You can simply make an array of 4 elements per point and then call from_array:

n_points = 100
color = 10.0
prgb = pcl.PointCloud_PointXYZRGB();
prgb_array = np.zeros((n_points, 4), dtype=np.float32);
prgb.from_array(prgb_array)
prgb[10][3] = color

**Comment by Sirokujira** [comment]
@niranjanreddy891 

A detailed explanation of laspy is as follows.
http://laspy.readthedocs.io/en/latest/

Below is a display code of pointcloud with RGB added.

As a caveat, we use PointCloud_PointXYZRGBA instead of PointCloud_PointXYZRGB.
(In the case of RGB, there is a problem with screen display.)

Replacing the laspyfilepath variable.

---

```python
from laspy import file
import numpy as np
import pcl
import pcl.pcl_visualization

f = file.File(laspyfilepath, mode='r')

# check las file version
# RGB contains
if f._header.data_format_id in (2, 3, 5):
    red = (f.red)
    green = (f.green)
    blue = (f.blue)
    # 16bit to convert 8bit data(data Storage First 8 bits case)
    red = np.right_shift(red, 8).astype(np.uint8)
    green = np.right_shift(green, 8).astype(np.uint8)
    blue = np.right_shift(blue, 8).astype(np.uint8)
    # (data Storage After 8 bits case)
    # red = red.astype(np.uint8)
    # green = green.astype(np.uint8)
    # blue = blue.astype(np.uint8)
    red = red.astype(np.uint32)
    green = green.astype(np.uint32)
    blue = blue.astype(np.uint32)
    rgb = np.left_shift(red, 16) + np.left_shift(green, 8) + np.left_shift(blue, 0)
    ptcloud = np.vstack((f.x, f.y, f.z, rgb)).transpose()
    cloud = pcl.PointCloud_PointXYZRGBA()
    # set raw points
    # cloud.from_array(np.array(ptcloud, dtype=np.float32))
    # set point centered
    mean_param = np.concatenate([np.mean(ptcloud, 0)[0:3], np.zeros(1)])
    ptcloud_centred = ptcloud - mean_param
    # print(ptcloud_centred)
    cloud.from_array(np.array(ptcloud_centred, dtype=np.float32))

    ## Visualization
    visual = pcl.pcl_visualization.CloudViewing()
    visual.ShowColorACloud(cloud, b'cloud')

    v = True
    while v:
        v=not(visual.WasStopped())
```

**Comment by niranjanreddy891** [comment]
Thanks for the reply @Sirokujira, but there is no visualization window. I mean when I am running this program, it can't display the window output where I can see the visualization

**Comment by niranjanreddy891** [comment]
@Sirokujira, can you help me in this issue.

**Comment by niranjanreddy891** [comment]
Can anyone help me with this code which @Sirokujira has shared?

**Comment by Sirokujira** [comment]
pcl.pcl_visualization use windows os and pcl 1.8.1 only

and

modified setup.py remove comment(#). and rebuild setup.py.
```python
      packages=[
                "pcl",
                # "pcl.pcl_visualization",
      ],
```

**Comment by niranjanreddy891** [comment]
If I am not wrong, I modified `pcl_visualization.py`
But still it is not working. I am attaching a screenshot, please go through it.
![Scrrenshot](https://user-images.githubusercontent.com/33854825/37456135-b1300084-2864-11e8-8643-90e473b9baa5.png)

Please guide me how to solve this issue

**Comment by niranjanreddy891** [comment]
I am using win-7 64 bit with pcl-1.8.1.

**Comment by niranjanreddy891** [comment]
@Sirokujira, can you please help me in this issue. This is my academic project. Its very urgent. Sorry for asking to many questions.

**Comment by Sirokujira** [comment]
There are things I want to check about some items.
1. About how to install python-pcl

    1-a. Installation from the conda package?

         If you are building a source code package, you need to delete it once.

         You do not need to set environment variables.

         When installing the package of https://github.com/ccordoba12/pcl-conda-recipes
         * There is no visual.
         * It is based on 0.2. [Correspondence before Forking the Code of 0.3]

         When installing the package of https://github.com/Sirokujira/pcl-conda-recipes
         * Visual makes it to correspond in all OS environment.
         * It is based on 0.3.0 rc.
         * Installation on windows 2.7 is not possible [Because it assumes build on VS 2015]

    1-b. Installation from source code

          It is necessary to make the following items as a prerequisite for building in the Windows environment.

          1-b-1. It is necessary to set environment variables. 

          (https://github.com/strawlab/python-pcl#set-before-environment-variable)

          ex. Setting with PCL 1.8.1

              * set PCL_ROOT=C:\Program Files\PCL 1.8.1

              * set PATH=$(PCL_ROOT)/bin/;$(OPEN_NI2_ROOT)/Tools;$(VTK_ROOT)/bin;%PATH%

          1-b-2. Install OpenNI 2 in the installation from PCL/3rd Party folder. (Windows only)

          1-b-3. It is necessary to download pkg-config for Windows.

          Execution from PowerShell:

          (https://github.com/strawlab/python-pcl/blob/master/pkg-config/pkg-config_setting.txt)

          Execute Install-GTKPlus.ps1 from the command prompt (with administrator authority).

          * cd (Install-GTKPlus.ps1 placement place)

          * powershell -NoProfile -ExcutionPolicy Unrestricted. \Install-GTKPlus.ps1

          1-b-4. When using visual, before building
                 # "pcl.pcl_visualization" on line 638 of setup.py,
                 It is necessary to delete the comment of.

          Installation on python 2.7 is not possible [Because it assumes a build using VS 2015]


When moving python-pcl, only one method of building with conda-package or setup.py will work, 
so please delete all packages once when putting in again.

**Comment by niranjanreddy891** [comment]
@Sirokujira, I am encountering this error while installing using setup.py 
`setup.py: error: cannot find PCL, tried
    pkg-config pcl_common-1.8
    pkg-config pcl_common-1.7
    pkg-config pcl_common-1.6
    pkg-config pcl_common`

Can you please help me in this issue

**Comment by niranjanreddy891** [comment]
@Sirokujira, this is the error I am facing while building setup.py `e:\anaconda\installed\include\pyconfig.h(59): fatal error C1083: Cannot open inc
lude file: 'io.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildToo
ls\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\cl.exe' failed with exit st
atus 2`

**Comment by Sirokujira** [comment]
@niranjanreddy891 

1. Confirm that Windows SDK 10 is included. Or check whether it is SDK or damaged.

    (Check the Windows 10 SDK when installing the compiler.)
     or
    (Install it after downloading package of Windows SDK 10 from Microsoft)

* Use the latest version as possible

2. Update SetupTools

```cmd
    conda install -y -q setuptools
```


Reference

https://stackoverflow.com/questions/40018405/cython-cannot-open-include-file-io-h-no-such-file-or-directory/40037613

https://social.msdn.microsoft.com/Forums/en-US/b60eff91-8890-497f-883c-d2e45fb57afe/uwpvc14-dont-see-ioh-please-help-me?forum=wpdevelop

**Comment by niranjanreddy891** [comment]
@Sirokujira,  I am getting this error after performing the steps which you mentioned `LINK : fatal error LNK1181: cannot open input file 'kernel32.lib'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildToo
ls\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\link.exe' failed with exit
status 1181`

**Comment by Sirokujira** [comment]
@niranjanreddy891

1. Confirm whether the SDK is 10.0.15063.0. (There seems to be a bug at 10.0.14393.0)
2. Log off and log in again. (Because environment variables may not be reflected)
3. "1. If the phenomenon occurs even if you correspond to 2", 
   please set the following environment variables before starting by command prompt and building.

```cmd
set INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared
set LIB=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.15063.0\um\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.15063.0\ucrt\x64
```

Reference : 

https://developercommunity.visualstudio.com/content/problem/41913/link-fatal-error-lnk1104-in-empty-c-project.html

**Comment by niranjanreddy891** [comment]
@Sirokujira, I installed win-10 SDK with 10.0.16299.0 version. But i am facing this error `E:\PCL 1.8.1\include\pcl-1.8\pcl/io/impl/pcd_io.hpp(59): fatal error C1083: Cann
ot open include file: 'windows.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildToo
ls\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\cl.exe' failed with exit st
atus 2`

**Comment by niranjanreddy891** [comment]
@Sirokujira, I tried referring this [https://stackoverflow.com/questions/80788/fatal-error-c1083-cannot-open-include-file-windows-h-no-such-file-or-direc](link). But there is no `include folder` in my machine. Please see the image that I have attached
![No include folder](https://user-images.githubusercontent.com/33854825/37957098-baefdc9c-31ca-11e8-8f37-45d7d1d87a5f.png)

**Comment by Sirokujira** [comment]
@niranjanreddy891

C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt

Please check if there is windows.h in any of the above folders.

*1 If it does not exist, there is a possibility that the SDK installation has failed, so you need to reinstall it.

*2 If it exists outside the um folder, it must be added to the setting item in the environment variable with the previous set command.

*3 For 10.0.15063.0, there is a "windows.h" file in "C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0¥um".

If the file exists, there is a possibility that the file itself can not be accessed.
After launching command prompt with administrator privileges, execute setup.py build.

Reference destination

https://hero.handmade.network/forums/code-discussion/t/2863-day_001_-_setting_up_the_windows_build_-_fatal_error_c1083__cannot_open_include_file__windows.h__no_

**Comment by niranjanreddy891** [comment]
Now I am getting this error `LINK : fatal error LNK1158: cannot run 'rc.exe'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildToo
ls\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\link.exe' failed with exit
status 1158`

**Comment by Sirokujira** [comment]
@niranjanreddy891

It seems that rc.exe reference does not work well when using Visual Studio 2017 by itself.
(It seems that it will work if there is another version of Visual Studio)

You need to do one of the items described below.
1. Copy and paste all the contents of the folders below.

Copy C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\x86
Paste to C:\Program Files (x86)\Windows Kits\10\bin\x86

Copy C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\x64
Paste to C:\Program Files (x86)\Windows Kits\10\bin\x64

2. Launch Visual Studio 2017 installer and add check of VC ++ 2015.3 v 140 tool set (x86, x64)

Reference

https://stackoverflow.com/questions/14372706/visual-studio-cant-build-due-to-rc-exe

**Comment by niranjanreddy891** [comment]
Same error as before. I did restart my pc but no luck `LINK : fatal error LNK1158: cannot run 'rc.exe' error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildToo ls\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\link.exe' failed with exit status 1158`

**Comment by niranjanreddy891** [comment]
@Sirokujira, I solved the issue. I installed `VC++ 2017 version 15.5 v14.12 toolset` from `visual studio 2017`

But the problem is with installation using setup.py. It throws error 
`error: package directory 'pcl\pcl_visualization' does not exist`
when I use `python setup.py install`

**Comment by Sirokujira** [comment]
@niranjanreddy891

1. Restore the contents of setup.py.
   (# "pcl.pcl_visualization")

2. Confirmation with conda list.

```cmd
conda list
```

When python-pcl does not exist on display
Please do the following correspondence.

```cmd
python setup.py bdist_wheel
pip install dist/python_pcl-0.3-cp36-cp36m-win_amd36.whl
```

**Comment by niranjanreddy891** [comment]
@Sirokujira, when I am using `python setup.py bdist_wheel` this command , it throws `error: package directory 'pcl\pcl_visualization' does not exist`. I ran `conda list` command it doesn't have `python-pcl`

**Comment by Sirokujira** [comment]
@niranjanreddy891

Please return "pcl.pcl_visualization" described in "setup.py" to its original state.
(Because the corresponding item in "setup.py" described earlier was wrong)

**Comment by niranjanreddy891** [comment]
I changed it by placing comment near `pcl.pcl_visualization`. I am getting this error `LINK : fatal error LNK1158: cannot run 'rc.exe'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildToo
ls\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\link.exe' failed with exit
status 1158`

**Comment by niranjanreddy891** [comment]
@Sirokujira, I installed pcl successfully. But I need visualization in RGB colors which is my primary requirement. The code which you mentioned didn't work.

**Comment by CQUlds** [comment]
@niranjanreddy891 hello,  have you solved this problem? I meet the problem like you.  This is my code and result:
cloud = pcl.load_XYZRGB('E:/python test/point cloud/all.pcd')
visual = pcl.pcl_visualization.CloudViewing()
visual.ShowColorCloud(cloud, b'cloud')

Failed to find match for field 'rgb'.

**Comment by niranjanreddy891** [comment]
Try using RGBA instead of RGB. It should work

**Comment by CQUlds** [comment]
@niranjanreddy891 Thank you! Does this mean that I need to convert my point cloud file to the PCD file of XYZRBGA?
