### ISSUE TITLE
PCL installation error using setup.py

### ISSUE THREAD

**Issue by niranjanreddy891** [strawlab/python-pcl#180]
I am facing this issue while installing pcl using setup.py.
Can anyone please suggest me how to solve this. I am confused on how to set the path. -:)
 
![This is the error](https://user-images.githubusercontent.com/33854825/37815092-79db7340-2e93-11e8-9057-06cb4f14b10f.png)

**Comment by scizors** [comment]
same issue I cannot able to instal python modules

I am using windows 10
Case2. use 1.8.1
PCL all in one 1.9.1
python version 3.5

issue

(pyrhon3.5) C:\Users\rsr5le\Desktop\python-pcl-master>python setup.py build_ext -i
cannot find environment PKG_CONFIG_PATH
set environment PKG_CONFIG_PATH=C:\Program Files\PCL 1.8.1\lib\pkgconfig;C:\Program Files\PCL 1.8.1\3rdParty\FLANN\lib\pkgconfig;C:\Program Files\PCL 1.8.1\3rdParty\Eigen\lib\pkgconfig;
C:\Users\rsr5le\Desktop\python-pcl-master\pkg-config\pkg-config.exe
Traceback (most recent call last):
File "setup.py", line 152, in 
if subprocess.call(['.\pkg-config\pkg-config.exe', 'pcl_common%s' % pcl_version]) == 0:
File "C:\Users\rsr5le.conda\envs\pyrhon3.5\lib\subprocess.py", line 247, in call
with Popen(*popenargs, **kwargs) as p:
File "C:\Users\rsr5le.conda\envs\pyrhon3.5\lib\subprocess.py", line 676, in init
restore_signals, start_new_session)
File "C:\Users\rsr5le.conda\envs\pyrhon3.5\lib\subprocess.py", line 957, in _execute_child
startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

(pyrhon3.5) C:\Users\rsr5le\Desktop\python-pcl-master>
