### ISSUE TITLE
Error while installing using setup.py

### ISSUE THREAD

**Issue by niranjanreddy891** [strawlab/python-pcl#182]
`(base) E:\Anaconda\pcl-package\pcl-1.8.1>python setup.py install
set environment PKG_CONFIG_PATH=E:\new-pcl\PCL-1.8.1\PCL 1.8.1\bin;E:\new-pcl\PC
L-1.8.1\PCL 1.8.1\3rdParty\OpenNI2\Tools;E:\new-pcl\PCL-1.8.1\PCL 1.8.1\3rdParty
\VTK\bin;
E:\Anaconda\pcl-package\pcl-1.8.1\pkg-config\pkg-config.exe
setup.py: error: cannot find PCL, tried
    pkg-config pcl_common-1.8
    pkg-config pcl_common-1.7
    pkg-config pcl_common-1.6
    pkg-config pcl_common`

**Comment by Sirokujira** [comment]
@niranjanreddy891

1. Does E:\Anaconda\pcl-package\pcl-1.8.1\pkg-config\pkg-config.exe exist?
2. Does the folder exist in E:\new-pcl\PCL-1.8.1\PCL 1.8.1?
3. Have you set the folder path to the environment variable PCL_ROOT?
   set PCL_ROOT=E:\new-pcl\PCL-1.8.1\PCL 1.8.1

4. Delete the environment variable PKG_CONFIG_PATH, or make the following settings.
   set PKG_CONFIG_PATH=%PCL_ROOT%\lib\pkgconfig;%PCL_ROOT%\3rdParty\FLANN\lib\pkgconfig;%PCL_ROOT%\3rdParty\Eigen\lib\pkgconfig

5. Is there a pc file in the E:\new-pcl\PCL-1.8.1\PCL 1.8.1\lib\pkgconfig folder?

* pkg-config search pc files.

**Comment by niranjanreddy891** [comment]
Thanks for the reply @Sirokujira, the files which you mentioned are there correctly. But now I am encountering this issue. when using `python setup.py build_ext -i`
This is the error 
`e:\anaconda\installed\include\pyconfig.h(59): fatal error C1083: Cannot open inc
lude file: 'io.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildToo
ls\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\cl.exe' failed with exit st
atus 2`

**Comment by niranjanreddy891** [comment]
I installed visual c++ build tools in `c:\` and pcl which contains `setup.py` in `e:\`.

**Comment by niranjanreddy891** [comment]
It throws error while building setup.py `LINK : fatal error LNK1104: cannot open file 'libboost_date_time-vc141-mt-1_64.l
ib'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildToo
ls\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\link.exe' failed with exit
status 1104`

**Comment by Sirokujira** [comment]
When using Python 3.6,
"Visual studio 2017/2015" If both are installed,
We will use the "Visual Studio 2017" compiler preferentially.

As a countermeasure, you need to do either 1 or 2.
1. Build a virtual environment containing python 3.5 of conda and then build it there.
```cmd
       conda create -n py35 python=3.5
       conda activate py35
```
   (We will only use the vs 2015 compiler at build time.)

2. Uninstall the current PCL module and install VS2017 version.

**Comment by niranjanreddy891** [comment]
Can I use this command `conda create -n py36 python=3.6`
`conda activate py36`

Since I am using python 3.6

**Comment by niranjanreddy891** [comment]
@Sirokujira, I tried 1st method which you mentioned in the above comment. But I am facing this error 
`LINK : fatal error LNK1104: cannot open file 'libboost_date_time-vc141-mt-1_64.l ib' error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildToo ls\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX64\\x64\\link.exe' failed with exit status 1104`

**Comment by niranjanreddy891** [comment]
`e:\anaconda\installed\include\pyconfig.h(59): fatal error C1083: Cannot open inc
lude file: 'io.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildToo
ls\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\cl.exe' failed with exit st
atus 2`

I am facing this error while using `python setup.py build_ext -i`

**Comment by niranjanreddy891** [comment]
@Sirokujira, I installed pcl-1.8.1 2017 version from [http://unanancyowen.com/en/pcl181/](here). I installed visual c++ build tools from [https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017
](Build Tools for Visual Studio 2017).

**Comment by CUSH07** [comment]
my problem is same as yours, could u tell me how to solve it please?

**Comment by CUSH07** [comment]
set environment PKG_CONFIG_PATH=D:\PCL_Project\python-pcl-master\pkg-config\pkg-config.exe;"D:\PCL_Project\PCL 1.8.1\3rdParty\FLANN\lib\pkgconfig;";"D:\PCL_Project\PCL 1.8.1\3rdParty\Eigen\lib\pkgconfig;";"D:\PCL_Project\PCL 1.8.1\lib\pkgconfig;";
D:\PCL_Project\python-pcl-master\pkg-config\pkg-config.exe
setup.py: error: cannot find PCL, tried
    pkg-config pcl_common-1.8
    pkg-config pcl_common-1.7
    pkg-config pcl_common-1.6
    pkg-config pcl_common

**Comment by CUSH07** [comment]
set environment PKG_CONFIG_PATH=D:\PCL_Project\python-pcl-master\pkg-config\pkg-config.exe;"D:\PCL_Project\PCL 1.8.1\3rdParty\FLANN\lib\pkgconfig;";"D:\PCL_Project\PCL 1.8.1\3rdParty\Eigen\lib\pkgconfig;";"D:\PCL_Project\PCL 1.8.1\lib\pkgconfig;";
D:\PCL_Project\python-pcl-master\pkg-config\pkg-config.exe
setup.py: error: cannot find PCL, tried
    pkg-config pcl_common-1.8
    pkg-config pcl_common-1.7
![TIM截图20191115215057](https://user-images.githubusercontent.com/52816930/68948059-07a5ae00-07f2-11ea-9be1-4a309bb24301.png)

    pkg-config pcl_common-1.6
    pkg-config pcl_common
