### ISSUE TITLE
Installing on windows

### ISSUE THREAD

**Issue by mazoku** [strawlab/python-pcl#19]
Hi everybody!

I'm trying to install python-pcl on win7 64bit. I installed the PCL1.5 using the prebuilt binaries (32bit version since I'am using 32bit Python). Then I tried run the setup.py and get stuck on the following error:
LINK : fatal error LNK1181: cannot open input file 'usb-1.0.lib' error: command '"c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\link.exe"' failed with exit status 1181

Can anybody help, please?

**Comment by niranjanreddy891** [comment]
`conda install -c ccordoba12 python-pcl`
Try this@mazoku
