### ISSUE TITLE
libpcl_registration.so.1.8 no such file or directory

### ISSUE THREAD

**Issue by TheMikeyR** [strawlab/python-pcl#196]
Systeminfo: Ubuntu 16.04
Kernel: 4.13.0-39-generic

Installed VTK and PCL through this [guide](https://askubuntu.com/questions/916260/how-to-install-point-cloud-library-v1-8-pcl-1-8-0-on-ubuntu-16-04-2-lts-for) succesfully, I've followed 16.04 steps and the validation completed. 

Then I've cloned this repository and ran ./build.sh which also completes but under the tests it fails all of them due to an importerror.
I've installed while being in a virtual environment (created with anaconda)

```
ERROR: Failure: ImportError (libpcl_registration.so.1.8: cannot open shared object file: No such file or directory)
```

Any clue on how to solve this issue ?

**Comment by j96w** [comment]
Have you tried "ldconfig"?

**Comment by TheMikeyR** [comment]
It managed to compile now, maybe due to ldconfig or reboot. Thanks!
