### ISSUE TITLE
Error while importing pcl

### ISSUE THREAD

**Issue by niranjanreddy891** [strawlab/python-pcl#201]
When I am using `import pcl`, it throws this error `ImportError: DLL load failed: The specified procedure could not be found.` I am using pcl-1.8.1, python-3.6 with windows-7 64 bit installed.

**Comment by juxiangwu** [comment]
Had the same problem. env: python 3.6, windows 10 x64, pcl 1.8.1.

**Comment by niranjanreddy891** [comment]
Can you please elaborate your error. Also how you installed python-pcl. I mean command used to install python-pcl. :)

**Comment by juxiangwu** [comment]
Now,I have solved the problem.Just missing C:\Program Files\OpenNI2\Samples\Bin\OpenNI2.dll.Copy OpenNI2.dll to Lib\site-packages\python_pcl-0.3-py3.6-win-amd64.egg\pcl

**Comment by niranjanreddy891** [comment]
Ok. :+1:

**Comment by wassname** [comment]
OpenNI2.dll worked for me to, I was using [a whl from build 1.0.59, commit 8fd7bb2c9b5eff2fece](https://ci.appveyor.com/project/Sirokujira/python-pcl-iju42/build/1.0.59/job/p6dwqxcu4iwuqc1n),. The exact wheel is [python_pcl-0.3-cp36-cp36m-win_amd64.whl ](https://ci.appveyor.com/api/buildjobs/p6dwqxcu4iwuqc1n/artifacts/dist%2Fpython_pcl-0.3-cp36-cp36m-win_amd64.whl)

**Comment by jsfraser1** [comment]
I just wanted to report that this is still true one year later. I took the latest wheel to quickly install on windows, and I had to install OpenNI2 to get the dll and I pasted it in the pcl folder; it solved my problem.

**Comment by syjiang05** [comment]
Just record that OpenNI2.dll also worked for me now, and I was using python_pcl-0.3-cp36-cp36m-win_amd64.whl. After downloaded and installed OpenNI2 from [https://structure.io/openni](url), copy "C:\Program Files\OpenNI2\Redist\OpenNI2.dll" to  the pcl folder ("C:\Software\Anaconda3\envs\test\Lib\site-packages\pcl" in my case).

**Comment by keineahnung2345** [comment]
The conda installation doesn't work for me on Windows, when I use `pip install C:\Users\mimif\Downloads\python_pcl-0.3-cp36-cp36m-win_amd64.whl`, everything works fine.
