### ISSUE TITLE
link Visual Studio 2015 C++ Compiler Tools broken

### ISSUE THREAD

**Issue by martinResearch** [strawlab/python-pcl#206]
Hello, 

the readme needs beening updated as the link to Visual Studio 2015 C++ Compiler Tools is broken. Is it still the expected version of the windows tools on windows ?

**Comment by niranjanreddy891** [comment]
@martinResearch, can you please provide the detailed report of the error. Also please specify which version of windows are you using?
This could help us to resolve the issue.

**Comment by martinResearch** [comment]
i am using windows 10 with Firefox, but i don't understand how that would help in solving the broken link problem. 
when i click on the Visual Studio 2015 C++ Compiler Tools link in the readme.md page it goes to
http://landinghub.visualstudio.com/visual-cpp-build-tools
and it get me to a page with 
"The HubSpot account associated with the domain "landinghub.visualstudio.com" has expired."

**Comment by niranjanreddy891** [comment]
You can download it from [here](https://blogs.msdn.microsoft.com/vcblog/2016/03/31/announcing-the-official-release-of-the-visual-c-build-tools-2015/)

**Comment by martinResearch** [comment]
thanks, should i do i pull request to fix the link in the readme ?

**Comment by martinResearch** [comment]
actually, when i click on the  link you gave it gets me to another page where i can doznload the Build Tools for Visual Studio 2017 , not 2015.  So that should be modifed in the readme too, and hopefull that work with the 2017 tools too

**Comment by niranjanreddy891** [comment]
@martinResearch, the link which I gave you have 2015 version too. Please check it

**Comment by niranjanreddy891** [comment]
@martinResearch, close the issue if the problem is solved. :)
