### ISSUE TITLE
generating wheels with appveyor

### ISSUE THREAD

**Issue by martinResearch** [strawlab/python-pcl#207]
I had some difficulties installing python-pcl (the link to Visual Studio 2015 C++ Compiler Tools is boken) and i had to edit the setup.py file to add the directories containing the various windows header and lib folders.
The installation on windows could be greatly simplified by  generating wheels that contains precompiled binaries generated on appveyor.com, thus avoiding the need for the user to install windows toolkits and other dependencies. There is a example here https://github.com/ogrisel/python-appveyor-demo that could be followed. I guess we could register the wheels to pypi in order to allow an easy installation though 
pip install python-pcl

**Comment by martinResearch** [comment]
similarly we travis could be use to generate wheels for linux
https://docs.travis-ci.com/user/deployment/pypi/

**Comment by niranjanreddy891** [comment]
@martinResearch, since you have the issue with visual studio 2015 c++ compiler tools, you can find it [here](https://github.com/strawlab/python-pcl/issues/206)
