### ISSUE TITLE
Fail to test the example for smoothing

### ISSUE THREAD

**Issue by CQUlds** [strawlab/python-pcl#222]
I tried to run the example code for smoothing but failed:

import pcl
p = pcl.load("table_scene_lms400.pcd")
fil = p.make_statistical_outlier_filter()
fil.set_mean_k (50)
fil.set_std_dev_mul_thresh (1.0)
fil.filter().to_file("inliers.pcd")

The result is as follow:

Traceback (most recent call last):
  File "E:/python test/point cloud/test.py", line 6, in <module>
    fil.filter().to_file("inliers.pcd")
  File "pcl\pxi\PointCloud_PointXYZ_180.pxi", line 271, in pcl._pcl.PointCloud.to_file (pcl\_pcl_180.cpp:60567)
TypeError: expected bytes, str found

**Comment by nicolas-chaulet** [comment]
Hi @CQUlds , I think you need to give bytes instead of strings to the `to_file` method. Trye the following:
`fil.filter().to_file(b'inliers.pcd')`

**Comment by CQUlds** [comment]
@nicolas-chaulet  Ha, thank you, it works well. I'm not familiar with this yet.

**Comment by jafekb** [comment]
https://stackoverflow.com/questions/7585435/best-way-to-convert-string-to-bytes-in-python-3

how to convert stored strings to bytes

**Comment by jafekb** [comment]
And if instead you have a string where the output name is stored, such as `out_name`, the way to convert that to bytes is by:
`fil.filter().to_file(out_name.encode('utf-8'))`
