### ISSUE TITLE
Debian package?

### ISSUE THREAD

**Issue by mehditlili** [strawlab/python-pcl#230]
Thanks for these awesome python ports.
Do you plan to release it as a debian package for linux?
I think the possibility to install it with apt-get will make it much more accessible.

**Comment by jspricke** [comment]
I've filled an ITP and will upload a package soon:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909221

**Comment by jspricke** [comment]
Done: https://packages.debian.org/source/unstable/python-pcl

Can you close this?
