### ISSUE TITLE
build issue on Ubuntu 18.04

### ISSUE THREAD

**Issue by tianer2820** [strawlab/python-pcl#238]
I'm trying to compile python-pcl on Ubuntu 18.04
with:
pcl 1.8
cython 0.25

It seems like setup.py didn't find the pcl lib on my computer, but I did installed it, it's in /usr/local/include/pcl-1.8/pcl
do any one have the same problem?

here is the error code:

> `Package pcl_visualization-1.8 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `pcl_visualization-1.8.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'pcl_visualization-1.8' found
> Package pcl_visualization-1.8 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `pcl_visualization-1.8.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'pcl_visualization-1.8' found
> Package pcl_visualization-1.8 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `pcl_visualization-1.8.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'pcl_visualization-1.8' found
> Package pcl_visualization-1.8 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `pcl_visualization-1.8.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'pcl_visualization-1.8' found
> Package pcl_visualization-1.8 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `pcl_visualization-1.8.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'pcl_visualization-1.8' found
> running install
> running bdist_egg
> running egg_info
> writing requirements to python_pcl.egg-info/requires.txt
> writing python_pcl.egg-info/PKG-INFO
> writing top-level names to python_pcl.egg-info/top_level.txt
> writing dependency_links to python_pcl.egg-info/dependency_links.txt
> reading manifest file 'python_pcl.egg-info/SOURCES.txt'
> writing manifest file 'python_pcl.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> creating build/lib.linux-x86_64-2.7
> creating build/lib.linux-x86_64-2.7/pcl
> copying pcl/__init__.py -> build/lib.linux-x86_64-2.7/pcl
> running build_ext
> skipping 'pcl/_pcl_180.cpp' Cython extension (up-to-date)
> building 'pcl._pcl' extension
> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-nbjU53/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DEIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET=1 -I/home/toby/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/ni -I/usr/include/vtk-5.8 -I/usr/local/include/vtk-8.0 -I/usr/local/Cellar/vtk/8.0.1/include -I/usr/include/python2.7 -c pcl/_pcl_180.cpp -o build/temp.linux-x86_64-2.7/pcl/_pcl_180.o
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> In file included from pcl/_pcl_180.cpp:455:0:
> pcl/boost_shared_ptr_assign.h:1:10: fatal error: pcl/point_cloud.h: No such file or directory
>  #include <pcl/point_cloud.h>
>           ^~~~~~~~~~~~~~~~~~~
> compilation terminated.
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> build.sh: line 3: nosetests: command not found`

**Comment by tianer2820** [comment]
well I solved this by copying /usr/local/include/pcl-1.8/* to /usr/local/include/

**Comment by git-chenjiqing** [comment]
copying /usr/local/include/pcl-1.8/* to /usr/local/
@tianer2820
