### ISSUE TITLE
error in installing python-pcl on raspberry pi 3 B+

### ISSUE THREAD

**Issue by hebahakim** [strawlab/python-pcl#259]
Hello
I am using Raspberry pi 3 B+ with raspbian stretch os and RAM =128GiB. I increased the size of swap file but i still can not install python-pcl on Raspberry Pi with the following error:

/usr/local/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
In file included from pcl/_pcl_180.cpp:499:0:
/usr/local/include/pcl-1.8/pcl/sample_consensus/sac_model.h: In instantiation of ‘bool pcl::SampleConsensusModel<PointT>::isModelValid(const VectorXf&) [with PointT = pcl::PointXYZ; Eigen::VectorXf = Eigen::Matrix<float, -1, 1>]’:
pcl/_pcl_180.cpp:108412:1:   required from here
/usr/local/include/pcl-1.8/pcl/sample_consensus/sac_model.h:518:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (model_coefficients.size () != model_size_)
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
virtual memory exhausted: Cannot allocate memory
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

any help will be appreciated.

**Comment by niranjanreddy891** [comment]
@hebahakim, this library won't support for **raspbian stretch os**. Go through documentation for more information.

**Comment by hebahakim** [comment]
thanks for your reply.

**Comment by niranjanreddy891** [comment]
@hebahakim, please close the issue.
