### ISSUE TITLE
Not able to import pcl

### ISSUE THREAD

**Issue by kevlem94** [strawlab/python-pcl#283]
Hello everybody,

I have installed python-pcl with the following command : `conda install -c sirokujira python-pcl --channel conda-forge` from Ananconda prompt opened as Administrator.
I have also installed PCL 1.8.1 libraries from the All-in-One installer. I work with Windows 7 64bits, Anaconda3, Spyder (Python 3.6).
I want to import python-pcl package with the command `import pcl` but when I try this, I obtain the following error message : 

 Traceback (most recent call last):

  File "<ipython-input-1-1e2e5cb12ae8>", line 1, in <module>
    import pcl

  File "D:\klemiere\Anaconda3\lib\site-packages\python_pcl-0.3-py3.6-win-amd64.egg\pcl\__init__.py", line 6, in <module>
    from ._pcl import *

ImportError: DLL load failed:  The specified module could not be found.

I read some issue reports on GitHub, suggesting to add OpenNI2 path to environment variable, but it doesn't change anything.

In order to be sure of adding the path correctly, I show you the "PATH" environment variable like it is written in my system: 

PATH = $(PCL_ROOT)/bin/;$(OPEN_NI2_ROOT)/Tools;$(VTK_ROOT)/bin;C:\Program Files\OpenNI2\Samples\Bin;%PATH%

with : 

PCL_ROOT = C:\Program Files\PCL 1.8.1

Do you have any idea about this problem ?

I'm new on GitHub, so if I have forgotten something, please forgive me for that.

Thanks in advance for your help

**Comment by kevlem94** [comment]
Finally I resolved the issue. In some cases, python-pcl package seems to be DLL librairies missing. To find these DLL files, you can install `pclpy` package, which is a kind of equivalent of `python-pcl`, but doesn't use the same syntax in the python script. However, if you install `pclpy` (`pip install pclpy`), you will have the missing DLL files in its dependencies (sites-packages/pclpy_dependencies/bin). In your python script, in first import the pclpy package (`import pclpy`) and its pcl dependencies (`from pclpy import pcl`) and then you can import the python-pcl package via `import pcl`, and the error message will not appear any more. You can also copy/paste the missing DLL files in `python-pcl` depencies if you don't want to import `pclpy`.

I hope this will be helpful for somebody,

**Comment by laiming997** [comment]
> Finally I resolved the issue. In some cases, python-pcl package seems to be DLL librairies missing. To find these DLL files, you can install `pclpy` package, which is a kind of equivalent of `python-pcl`, but doesn't use the same syntax in the python script. However, if you install `pclpy` (`pip install pclpy`), you will have the missing DLL files in its dependencies (sites-packages/pclpy_dependencies/bin). In your python script, in first import the pclpy package (`import pclpy`) and its pcl dependencies (`from pclpy import pcl`) and then you can import the python-pcl package via `import pcl`, and the error message will not appear any more. You can also copy/paste the missing DLL files in `python-pcl` depencies if you don't want to import `pclpy`.
> 
> I hope this will be helpful for somebody,

Hi , thank you very much for your solution, I have found many solution to try ,but it's all failed . And I also install the pclpy package, after import the pclpy it succeed to import the pcl. But if I want to copy the dependencies, where should I put the dependencies in the python-pcl.  I have tried to copy to the folder `...\python_pcl-0.3.0rc1-py3.6-win-amd64.egg\Lib\site-packages\pcl`,where has some dll file in but it's also failed to import pcl directly. 

>
