### ISSUE TITLE
Undefined symbol error when importing pcl

### ISSUE THREAD

**Issue by glucenag** [strawlab/python-pcl#329]
## Your Environment

* Operating System and version: Ubuntu 18.04
* Compiler: (do not know what this is ?)
* PCL Version: 1.8.1
* Cython Version: 0.29.14 (py36he1b5a44_0 from conda-forge)

## Context

For some project I need to use the python-pcl package, but somehow I am stuck and cannot import pcl. Opening up a python shell and trying `import pcl` spits an error (see below). 

Here are some details:

I am using (ana)conda3; I have a conda environment with python3.6, where I have installed cython (see version above) and python-pcl and other packages (see full list below). I installed python-pcl and pcl using conda. Same for cython and all other packages of course. Note that I of course take care that I open my python shell within my conda environment. 

Output of `~/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl$ ldd _pcl.cpython-36m-x86_64-linux-gnu.so | grep libpcl : `

```
libpcl_registration.so.1.8 => /home/glucenag/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl/./../../../libpcl_registration.so.1.8 (0x00007fd4504fa000)
	libpcl_segmentation.so.1.8 => /home/glucenag/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl/./../../../libpcl_segmentation.so.1.8 (0x00007fd44f673000)
	libpcl_features.so.1.8 => /home/glucenag/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl/./../../../libpcl_features.so.1.8 (0x00007fd44d0d0000)
	libpcl_ml.so.1.8 => /home/glucenag/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl/./../../../libpcl_ml.so.1.8 (0x00007fd44cea7000)
	libpcl_surface.so.1.8 => /home/glucenag/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl/./../../../libpcl_surface.so.1.8 (0x00007fd44c7ad000)
	libpcl_tracking.so.1.8 => /home/glucenag/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl/./../../../libpcl_tracking.so.1.8 (0x00007fd44c1cd000)
	libpcl_filters.so.1.8 => /home/glucenag/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl/./../../../libpcl_filters.so.1.8 (0x00007fd44b819000)
	libpcl_sample_consensus.so.1.8 => /home/glucenag/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl/./../../../libpcl_sample_consensus.so.1.8 (0x00007fd44a9df000)
	libpcl_visualization.so.1.8 => /home/glucenag/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl/./../../../libpcl_visualization.so.1.8 (0x00007fd44a6a7000)
	libpcl_io.so.1.8 => /home/glucenag/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl/./../../../libpcl_io.so.1.8 (0x00007fd44a350000)
	libpcl_search.so.1.8 => /home/glucenag/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl/./../../../libpcl_search.so.1.8 (0x00007fd449f98000)
	libpcl_kdtree.so.1.8 => /home/glucenag/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl/./../../../libpcl_kdtree.so.1.8 (0x00007fd449c4f000)
	libpcl_octree.so.1.8 => /home/glucenag/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl/./../../../libpcl_octree.so.1.8 (0x00007fd448f11000)
	libpcl_common.so.1.8 => /home/glucenag/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl/./../../../libpcl_common.so.1.8 (0x00007fd448c53000)
	libpcl_io_ply.so.1.8 => /home/glucenag/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl/./../../.././libpcl_io_ply.so.1.8 (0x00007fd43e6e3000)
```

where opm-finder is the name of my conda environment for this project. 

This is how I installed and compiled the PCL library:

```
sudo apt-get -y install g++ cmake cmake-gui doxygen mpi-default-dev openmpi-bin openmpi-common
sudo apt-get -y install libusb-1.0-0-dev libqhull* libusb-dev libgtest-dev
sudo apt-get -y install git-core freeglut3-dev pkg-config build-essential libxmu-dev libxi-dev
sudo apt-get -y install libphonon-dev libphonon-dev phonon-backend-gstreamer
sudo apt-get -y install phonon-backend-vlc graphviz mono-complete
sudo apt-get -y install qt5-default
sudo apt-get -y install libflann-dev

sudo apt-get -y install libflann1.9
sudo apt-get -y install libboost-dev
sudo apt-get -y install libeigen3-dev
```

then for VTK 8.1.1:

```
cd ~/Downloads
wget http://www.vtk.org/files/release/8.1/VTK-8.1.1.tar.gz
tar -zxvf VTK-8.1.1.tar.gz
cd VTK-8.1.1
mkdir build
cd build
cmake ..
make
sudo make install
```

and finally for PCL 1.8.1:

```
cd ~/Downloads
wget https://github.com/PointCloudLibrary/pcl/archive/pcl-1.8.1.tar.gz
tar -zxvf pcl-1.8.1.tar.gz
cd pcl-pcl-1.8.1
mkdir build
cd build
cmake ..
make
sudo make install
```

Subsequently doing an `ldconfig` is a success. This all comes from this: [https://stackoverflow.com/questions/58040066/how-to-compile-point-cloud-library-pcl-with-examples-ubuntu](url), which is where I followed the steps above. 

## Expected Behavior

It should import pcl from python-pcl. 

## Current Behavior

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/glucenag/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl/__init__.py", line 2, in <module>
    from ._pcl import *
ImportError: /home/glucenag/anaconda3/envs/opm-finder/lib/python3.6/site-packages/pcl/../../../libpcl_visualization.so.1.8: undefined symbol: _ZN3pcl9PCDReader4readERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_14PCLPointCloud2Ei
```

## Possible Solution

Really non idea. I have looked at many, many issues on this github already so please do not mark this as duplicate. 

A possible culprit is that before the afore mentionned install of PCL 1.8.1, I had tried installing the 1.8 version (from another post, in fact aimed at Ubuntu 16.04 and not my 18.04), and it had failed to build it. This and the fact that I am in fact running Ubuntu 18.04 lead me to finally try and install PCL in the way described above, which was apparently recommended for my Ubuntu 18.04.

I would be extremely grateful for any input. Please note again that I have looked at dozens of other issues similar to mine (similar error message), including a lot of them on this forum, and did not find anything helpful. 

I will be happy to post additional information if deemed relevant of course!

**Comment by hetolin** [comment]
Hi,Have you solve it? I meet the same question.I install python-pcl use conda install. But when I import pcl. I got the error:
ImportError: /home/hetolin/anaconda3/envs/grasp/lib/python3.6/site-packages/pcl/_pcl.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3pcl11ConcaveHullINS_8PointXYZEE21performReconstructionERNS_11PolygonMeshE
I tried many method.But they don't make sense

**Comment by glucenag** [comment]
Hey there. No, I did not solve it. We went another route, ultimately and I did not check back on this issue, sorry.

**Comment by ZhangXGe** [comment]
I also meet this question. Have you solved it? @hetolin 
@glucenag Did you find a replacement library? Can you share it?

**Comment by hetolin** [comment]
@ZhangXGe I did not solve it. I change to another library called opne3d, which is easier to use
