### ISSUE TITLE
How do I visualize a colored point cloud?

### ISSUE THREAD

**Issue by soulslicer** [strawlab/python-pcl#344]
Do I pass in a numpy matrix of size [N*6]. Doing that crashes however

Please give me a full example of how to display a color pointcloud using `viewer = pcl.pcl_visualization.PCLVisualizering()`

I need a full example. I have a [Nx3] matrix for XYZ and [Nx3] for RGB color

**Comment by soulslicer** [comment]
Bump

**Comment by themightyoarfish** [comment]
The first sentence in the Readme states 

> (all methods operate on PointXYZ)

dunno if that means nothing beyond XYZ is supported here.

**Comment by soulslicer** [comment]
what a garbage library lol. i ended up writing my own pybind wrappers to c++ pcl. waay easier than dealing with this shit
