### ISSUE TITLE
pcl installation error 

### ISSUE THREAD

**Issue by Yatim4Omar** [strawlab/python-pcl#345]
when trying to install pcl-python using setup.py or even pip install i get this error:
C:\Users\FARHAT\Downloads\python-pcl-master>python setup.py install
set environment PKG_CONFIG_PATH=C:\Program Files\PCL 1.9.1\lib\pkg-config
C:\Program Files\PCL 1.9.1\lib\pkgconfig\pkg-config\pkg-config.exe
setup.py: error: cannot find PCL, tried
    pkg-config pcl_common-1.9
    pkg-config pcl_common-1.8
    pkg-config pcl_common-1.7
    pkg-config pcl_common-1.6
    pkg-config pcl_common

i am  using windows10
PCL all in one 1.9.1
python version 3.7.6

**Comment by Yatim4Omar** [comment]
It turns out that the issue was related to GTK+.
It wasn't installed in my device, all i had to do was run the powershell script in pkg-config directory.

**Comment by lan-sky** [comment]
I have the same problem as you，but i dont  understand how you solved it. Can you give me more details

**Comment by lucy-yang1993** [comment]
I have the same problem with yours, and my system is ubuntu16.04,can you give me some advices?

**Comment by SwatiMatta** [comment]
@lucy-yang1993 were you able to solve the problem? I'm having the same issue.
