### ISSUE TITLE
get_point causes Abort

### ISSUE THREAD

**Issue by jiskattema** [strawlab/python-pcl#40]
The pointcloud.get_point function causes an abort instead; it should just throw an exception instead:
# !/usr/bin/python

import numpy as np
import pcl

a = np.zeros( [30,3], dtype=np.float32 )
p = pcl.PointCloud( a )

print p.get_point(10,10)

output:

terminate called after throwing an instance of 'pcl::IsNotDenseException'
  what():  Can't use 2D indexing with a unorganized point cloud
Aborted (core dumped)

**Comment by Sirokujira** [comment]
set numpy Array data is 2D.(set 3D data.)
