### ISSUE TITLE
python3-pcl import error

### ISSUE THREAD

**Issue by muttistefano** [strawlab/python-pcl#400]
Hello Everyone,
i am on Ubuntu 20.04.
I have installed the package python3-pcl, cause i could not build this repo using the libpcl(1.10) shipped on ubuntu 20.
When i import the pcl lib in python, i get the following error:
`
Traceback (most recent call last):
  File "example.py", line 8, in <module>
    import pcl
  File "/usr/lib/python3/dist-packages/pcl/__init__.py", line 2, in <module>
    from ._pcl import *
ImportError: /lib/x86_64-linux-gnu/libpcl_io.so.1.10: undefined symbol: libusb_set_option `

Does anyone know why?
Thanks

**Comment by muttistefano** [comment]
My bad,  i noticed now libpcl was linked to a wrong libusb library.
Thanks

**Comment by pk1996** [comment]
Hey could you briefly outline the steps you followed to install pcl
BTW is it PCL 1.10 or <1.10?? 
Thanks!
