### ISSUE TITLE
Installation on Ubuntu 20.04/Python 3.8.10

### ISSUE THREAD

**Issue by Petros626** [strawlab/python-pcl#411]
* Operating System and version: Ubuntu 20.04.04 LTS
* Compiler: g++ (Ubuntu 9.4.0-lubuntu1~20.04.1) 9.4.0
* PCL Version: 0.3.0~rc1+dfsg-8build3
* Cython Version: 0.29.14-0.1ubuntu3

Hey guys,

I am a little unsure whether the installation with sudo apt-get install python3-pcl worked correctly. It seems like it's u = unknown and n = not installed, but why?

So far I have only found one issue (https://github.com/strawlab/python-pcl/pull/407) that uses Ubuntu 20.04, but it seems to be a basic installation problem.

![Screenshot from 2022-05-11 07-36-53](https://user-images.githubusercontent.com/62354721/167776646-b89ade92-5f54-46ed-add6-60c77f9c3486.png)

**Comment by gaobaoding** [comment]
Hi @Petros626,

I'm also working on installing this python binding, however, I think it currently only supports till libpcl1.9.x. You need to manually install the 1.9.x version instead of apt-get

**Comment by Petros626** [comment]
I solved it months ago with another version
