### ISSUE TITLE
Impossible to install python-pcl

### ISSUE THREAD

**Issue by mianuel** [strawlab/python-pcl#52]
Hello,

I'm very exciting to use this module but I cannot install it. Could you help me.
## The errors during the installation process are:

Package openni-dev was not found in the pkg-config search path.
Perhaps you should add the directory containing `openni-dev.pc'
to the PKG_CONFIG_PATH environment variable
Package 'openni-dev', required by 'pcl_io', not found
Package openni-dev was not found in the pkg-config search path.
Perhaps you should add the directory containing`openni-dev.pc'
to the PKG_CONFIG_PATH environment variable
Package 'openni-dev', required by 'pcl_io', not found
Package openni-dev was not found in the pkg-config search path.
Perhaps you should add the directory containing `openni-dev.pc'
to the PKG_CONFIG_PATH environment variable
Package 'openni-dev', required by 'pcl_io', not found
Package openni-dev was not found in the pkg-config search path.
Perhaps you should add the directory containing`openni-dev.pc'
to the PKG_CONFIG_PATH environment variable
Package 'openni-dev', required by 'pcl_io', not found
running install
running build
running build_py
running build_ext
skipping 'pcl/_pcl.cpp' Cython extension (up-to-date)
building 'pcl._pcl' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c pcl/_pcl.cpp -o build/temp.linux-x86_64-2.7/pcl/_pcl.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
pcl/_pcl.cpp:346:29: fatal error: pcl/point_cloud.h: No such file or directory
 #include "pcl/point_cloud.h"
                             ^
## compilation terminated.

I'm using
Ubuntu 14.04
Cython 20.0
PCL 1.7.2

I really need this module to work and I will appreciate if you can help me.
Thank !!
Manu

**Comment by jaimesx** [comment]
I was searching for the problem also, and it was already fixed in newer pcl commits, the fix must be present in pcl-1.8.0rc1: 
https://github.com/PointCloudLibrary/pcl/commit/dc545ccf56067d7bc2f7a8563253706743f345ef

**Comment by GinaVulpes** [comment]
Hello everyone! 

I have the same problem on my Mac. 

**## The Error:**
Package openni-dev was not found in the pkg-config search path.
Perhaps you should add the directory containing `openni-dev.pc'
to the PKG_CONFIG_PATH environment variable
Package 'openni-dev', required by 'pcl_io-1.6', not found
Package openni-dev was not found in the pkg-config search path.
Perhaps you should add the directory containing `openni-dev.pc'
to the PKG_CONFIG_PATH environment variable
Package 'openni-dev', required by 'pcl_io-1.6', not found
Package openni-dev was not found in the pkg-config search path.
Perhaps you should add the directory containing `openni-dev.pc'
to the PKG_CONFIG_PATH environment variable
Package 'openni-dev', required by 'pcl_io-1.6', not found
Package openni-dev was not found in the pkg-config search path.
Perhaps you should add the directory containing `openni-dev.pc'
to the PKG_CONFIG_PATH environment variable
Package 'openni-dev', required by 'pcl_io-1.6', not found
Package openni-dev was not found in the pkg-config search path.
Perhaps you should add the directory containing `openni-dev.pc'
to the PKG_CONFIG_PATH environment variable
Package 'openni-dev', required by 'pcl_io-1.6', not found
running build_ext
skipping 'pcl/_pcl.cpp' Cython extension (up-to-date)
building 'pcl._pcl' extension
clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DEIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET=1 -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/ni -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pcl/_pcl.cpp -o build/temp.macosx-10.9-x86_64-2.7/pcl/_pcl.o
In file included from pcl/_pcl.cpp:455:
pcl/boost_shared_ptr_assign.h:1:10: fatal error: 'pcl/point_cloud.h' file not
      found


I got MacOs 10.12.6
and I installed pcl-1.6
Unfortunately, when I try to install OpenNI with the installer I get this msg: "This package is incompatible with this version of macOS and may fail to install." 

Any suggestions?

**Comment by Sirokujira** [comment]
I have not tried Mac version 1.6,
If you apply official packages,
OpenNI installation may not be done.

As confirmation,
From the link of http://pointclouds.org/downloads/macosx.html
Are you installing the OpenNI and Sensor packages?

**Comment by maneeshj** [comment]
@GinaVulpes  Were you able to resolve the issue ?
