### ISSUE TITLE
Dynamic linker error during `import pcl` on OS X with Anaconda

### ISSUE THREAD

**Issue by davesque** [strawlab/python-pcl#90]
I'm trying to use PCL on OS X with packages installed via Anaconda and python bindings provided by python-pcl.  I'm trying to install python-pcl and the required libraries in an Anaconda environment.  First, I tried to run `python setup.py install` inside the environment and it complained that it couldn't find the pkg-config binary.  I installed a version of pkg-config for OS X using Homebrew and tried installing again with the following command:

```
$ PKG_CONFIG_PATH="$CONDA_ENV_PATH/lib/pkgconfig" python setup.py install
```

This seemed to work fine, compiling successfully with a few warnings, then completing the setup.py installation.  However, when I try to import python-pcl in ipython, I get the following:

```
$ ipython
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:57:58)
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pcl
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-dcd28fa30e40> in <module>()
----> 1 import pcl

/Users/david/projects/python-pcl/pcl/__init__.py in <module>()
      1 # XXX do a more specific import!
----> 2 from ._pcl import *
      3
      4 import sys
      5

ImportError: dlopen(pcl/_pcl.so, 2): Library not loaded: @rpath/./libpcl_io.1.7.dylib
  Referenced from: /Users/david/projects/python-pcl/pcl/_pcl.so
  Reason: image not found
```

It looks like the linker doesn't know where to find the pcl libraries, but I'm not sure exactly how to fix this.  Any thoughts?

**Comment by ap--** [comment]
To fix the root cause, you should add "-install_name PATH-TO-YOUR-LIBPCL-INSTALLATION" to your linker flags when compiling libpcl.

To just fix the current issue:
use install_name_tool to fix `/Users/david/projects/python-pcl/pcl/_pcl.so` as explained [here](https://blogs.oracle.com/dipol/entry/dynamic_libraries_rpath_and_mac)

**Comment by davesque** [comment]
Just to be certain, am I supposed to add the `-install_name <path to libpcl installation>` switch when compiling libpcl _itself_ or when doing whatever compilation is necessary to run `python setup.py install` for python-pcl?  I just want to make sure that wasn't a typo.

**Comment by ap--** [comment]
Yes, when compiling libpcl.
Had the same issue with a different C-library and cython-wrapper on osx.
rpath searches relative to the working directory.
the troubleshooting section [here](https://github.com/matthew-brett/delocate) helped me quite a bit.

**Comment by davesque** [comment]
Thanks for the info.  I think this solved my problem.
